### ISSUE TITLE
SmdBlock - memory usage

### ISSUE THREAD

**Issue by p-hofmann** [p-hofmann/SMBEdit#5]
A SmdBlock object is made for every block. Storing the integer representing a block and using a SmdBlock only when needed would save a lot of space.

**Comment by Septaris** [comment]
We can do it using singleton metaclass and class manager. The idea is to return only a new instance for new blocks (new IDs) and return the existing instance if the ID is already used (like the logger class in the logging module).

An example of a working implementation (based on my previous work, compatible with python 2 and 3) :
[example.zip](https://github.com/p-hofmann/SMBEdit/files/695772/example.zip)

**Comment by p-hofmann** [comment]
I like that solution! I will play around with it when I find the time.
